# Generated by Django 5.2.5 on 2025-08-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='gmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
